version: '3.8'

services:
  # Temporal Services
  temporal-postgresql:
    container_name: temporal-postgresql
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
      POSTGRES_DB: temporal
    volumes:
      - temporal-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  temporal:
    container_name: temporal
    depends_on:
      - temporal-postgresql
    image: temporalio/auto-setup:1.22.0
    ports:
      - "7233:7233"
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=temporal-postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    image: temporalio/ui:2.18.0
    ports:
      - "8080:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000

  # MongoDB for application data
  mongodb:
    container_name: mongodb
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: applications
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  # Redis for caching and session management
  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # MailHog for email testing
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI

  # Backend API Service
  backend-api:
    container_name: backend-api
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=application-processing
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/applications?authSource=admin
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - FROM_EMAIL=noreply@example.com
      - PAYMENT_SERVICE_URL=http://payment-service:3002
      - DOCUMENT_SERVICE_URL=http://document-service:3003
    depends_on:
      - temporal
      - mongodb
      - redis
      - mailhog
      - payment-service
      - document-service
    volumes:
      - ./backend-api:/app
      - /app/node_modules

  # Payment Service
  payment-service:
    container_name: payment-service
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=development
      - PAYMENT_PROCESSING_DELAY_MS=2000
      - PAYMENT_SUCCESS_RATE=0.95
    volumes:
      - ./payment-service:/app
      - /app/node_modules

  # Document Service
  document-service:
    container_name: document-service
    build:
      context: ./document-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - NODE_ENV=development
      - DOCUMENT_GENERATION_DELAY_MS=3000
      - DOCUMENT_STORAGE_PATH=/app/generated-documents
      - DOCUMENT_BASE_URL=http://localhost:3003/documents
    volumes:
      - ./document-service:/app
      - /app/node_modules

  # Frontend Service
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - backend-api
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Temporal Worker
  temporal-worker:
    container_name: temporal-worker
    build:
      context: ./backend-api
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ENV=development
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_NAMESPACE=default
      - TEMPORAL_TASK_QUEUE=application-processing
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/applications?authSource=admin
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - FROM_EMAIL=noreply@example.com
      - PAYMENT_SERVICE_URL=http://payment-service:3002
      - DOCUMENT_SERVICE_URL=http://document-service:3003
    depends_on:
      - temporal
      - mongodb
      - redis
      - mailhog
      - payment-service
      - document-service
    volumes:
      - ./backend-api:/app
      - /app/node_modules

volumes:
  temporal-postgres-data:
  mongodb-data:
  redis-data:

networks:
  default:
    name: temporal-network